### ISSUE TITLE
[Bug]: GET call to Storage cost returns 500

### ISSUE THREAD

**Issue by michaelmumenthaler** [natron-io/tenant-api#53]
### What happened?

Any GET request to https://api.natron.io/api/v1/{Tenant}/costs/storage or https://api.natron.io/api/v1/costs/storage (no tenant) returns a server error 500. 

### Version

v0.2.4

**log in api**:
```bash
ERROR: 2022/02/01 09:38:42 costController.go:258: storage class longhorn-hdd-backup not found
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by janlauber** [comment]
I think I know, why this is happening:
The related storage class cost is not initialized via the env variables

**Comment by janlauber** [comment]
Setting env variables correctly solved the problem.
